### ISSUE TITLE
测试 Xposed Checker 发现六个检测点未通过 

### ISSUE THREAD

**Issue by HuRuWo** [sanfengAndroid/FakeXposed#12]
我先测试了一款检测xposed退出的软件 发现被检测了
随后又 测试了 Xposed Checker
发现有五个地方被检测了 是使用问题吗

**Comment by HuRuWo** [comment]
![image](https://user-images.githubusercontent.com/18063769/135037533-9342b641-0a93-4dc4-a05c-3243e3e5c3db.png)
![image](https://user-images.githubusercontent.com/18063769/135037575-c3b95706-f1b3-4108-b394-db1d3079ad1f.png)

**Comment by miyouzi** [comment]
我使用 Xposed Checker 也有5个不通过，请问如何配置才能解决？
